spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Li123456
    url: jdbc:mysql://120.25.165.180:3306/fruitery?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

server:
  port: 8090

mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: cn.edu.guet.weapp.bean